### ISSUE TITLE
ER diagram

### ISSUE THREAD

**Issue by BraMira** [BraMira/Mirjam-Spela#1]
Upamo,da pravilno popravljen ER diagram (@spelapovrzenic)

**Comment by jaanos** [comment]
Sedaj je v redu - edino `continent_id` ne potrebujeta pri državah, saj imata že relacijo na celino. Morda bi še relacijo `is_religion` drugače poimenoval (npr. `country_religion`). Odvisno od tega, kakšne podatke imata, bi morda na to relacijo lahko dali še atribut z npr. številom ali deležem ljudi v državi, ki pripada tej religiji.

**Comment by spelapovrzenic** [comment]
Najlepša hvala za pripombe. Diagram je tudi tokrat popravjen. Če pa bo še kaj za dodati, spremeniti, bova veseli vsakršne informacije, da še izboljšava. Lp
@BraMira

**Comment by jaanos** [comment]
Sedaj izgleda v redu, nimam drugih pripomb.
