### ISSUE TITLE
Problem uvozov

### ISSUE THREAD

**Issue by BraMira** [BraMira/Mirjam-Spela#2]
Datoteka iz mape uvoz (uvoz.r) ne deluje na računalnikih na faksu, ampak samo na mojem računalniku.

**Comment by jaanos** [comment]
Pri meni deluje. Verjetno je problem ta, da na faksu niso naložene zadnje verzije uporabljenih knjižnic. Poskusita (vsaka v svojem računu na faksu) namestiti knjižnice `rvest`, `dplyr` in `gsubfn` (v RStudiu izberita _Tools_ / _Install Packages..._ in tja napišita imena teh knjižnic).

**Comment by BraMira** [comment]
Doma mi vbistvu sploh ne najde knjižnice `dplyr`, da bi jo lahko inštalirala zato mi javlja napako.
`Error in library(dplyr) : there is no package called ‘dplyr’`.
Sem pa videla, da obstaja `plyr`,  a lahko mogoče tega raje uporabim?

**Comment by jaanos** [comment]
Katero različico R-ja pa uporabljaš? To lahko vidiš tako, da v konzolo napišeš `R.version.string`. Za uporabo (zadnje različice) knjižnice `dplyr` potrebuješ R različice vsaj 3.1.2 (trenutno najnovejša različica pa je 3.3.0).

**Comment by spelapovrzenic** [comment]
Tudi meni ne dela, imam pa verzijo 3.1.1, predvidevam da Mirjam tudi, saj smo v podobnem času si jo nameščali (leta 2014).

**Comment by jaanos** [comment]
Najbolje bo torej, če si namestita [zadnjo različico R-ja](http://stat.ethz.ch/CRAN/). Verjetno bo potrebno želene knjižnice potem znova namestiti.
