### ISSUE TITLE
Thumbs.db

### ISSUE THREAD

**Issue by jaanos** [BraMira/Mirjam-Spela#3]
Na repozitorij se vama je izmuznila datoteka `Thumbs.db`, ki pa tja ne sodi, saj gre za datoteko z ikonami, ki v Windowsih predstavljajo mapo. Svetujem torej, da jo pobrišeta z repozitorija, v `.gitignore` pa dodasta ustrezno vrstico, da se ne bo spet pojavila.

**Comment by spelapovrzenic** [comment]
Aha ok, najlepša hvala za opozorilo! Urejeno.
Lp
